version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: fuelphp-app
    ports:
      - "80:80"
    environment:
      FUEL_CRYPTO_KEY: ${FUEL_CRYPTO_KEY}
      FUEL_CRYPTO_IV: ${FUEL_CRYPTO_IV}
      FUEL_CRYPTO_HMAC: ${FUEL_CRYPTO_HMAC}
    volumes:
      - ../:/var/www/html/my_fuel_project
    networks:
      - fuelphp-network

  db:
    build:
      context: ../
      dockerfile: docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance-manager-db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - fuelphp-network

networks:
  fuelphp-network:
    driver: bridge

volumes:
  db_data:
